// AUTO-GENERATED by scripts/measure-stats.mjs — DO NOT EDIT BY HAND.
// Regenerated on every deploy from the real agentty binary, so the site can
// never drift from what actually ships. Last measured: 2026-09-04T08:22:58.878Z.

export const measuredStats = {
  "binarySizeBytes": 19074880,
  "binarySizeMB": "18.2 MB",
  "version": "0.7.0",
  "staticLinked": true,
  "coldStartMs": 3,
  "coldStartLabel": "~3 ms",
  "versionMs": 3.02,
  "helpMs": 3,
  "measuredAt": "2026-09-04T08:22:58.878Z",
  "source": "/home/ayush/.local/bin/agentty"
} as const;

export type MeasuredStats = typeof measuredStats;
